---
title: "TRIGR_scMulti_cell_type_curation"
output: html_document
---

```{r setup}

library(dplyr)
library(Seurat)
library(Signac)
library(sctransform)
library(future)
library(ggplot2)
library(readr)
library(tidyr)
library(tibble)
library(stringr)
library(GenomicRanges)
library(EnsDb.Hsapiens.v86)
library(GenomeInfoDb)
library(SingleCellExperiment)
library(ExperimentHub)
library(celldex)
library(SeuratDisk)
library(glmGamPoi)
library(future)
library(SingleR)

# multiome prep output directory
seurat_scmulti_prep <- ".../TRIGR_scMulti_so_prep"


# Top level output dir
project_dir <- "..."
# subanalysis output directory
subanalysis_name <- "TRIGR_scMulti_cell_type_curation"

options(
  future.globals.maxSize=100*1e9
)

# Output folder for this document
options(knitr.figure_dir = paste0(
  project_dir, "/",
  subanalysis_name
  )
)

source("knitr_common.r")
```

``` {r load_data}
so <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "so_integrated_no_batch_var.rds",
    sep = "/"
  )
)

so@meta.data <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "metadata.rds",
    sep = "/"
  )
)

so@commands <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "commands.rds",
    sep = "/"
  )
)

so@reductions$umap.wnn <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "wnn_umap_reduction.rds",
    sep = "/"
  )
)

so@reductions$umap.rna <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "rna_umap_reduction.rds",
    sep = "/"
  )
)

so@reductions$umap.atac <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "atac_umap_reduction.rds",
    sep = "/"
  )
)

so@reductions$CITE_seq_umap <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "CITE_seq_umap_reduction.rds",
    sep = "/"
  )
)

so[['macs2Peaks']] <- faster_readRDS(
  paste(
    seurat_scmulti_prep,
    "macs2_peaks_assay.rds",
    sep = "/"
  )
)

```


``` {r identify_cells}

DefaultAssay(so) <- "SCT"
Idents(so) <- "wsnn_res.0.8"

CD14_monocytes <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(0, 8, 18, 37))
CD16_monocytes <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(17, 35))
cDCs <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(14))
pDCs <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(19))


NK_CD56_bright <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(25, 33))
NK_CD56_dim <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(7, 23))

GD_T <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(11, 27))
proliferting_T <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(29))
NKT_cells <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(12))
Mem_eff_T_cells <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(10, 20))
CD8_T <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(2, 20, 21, 38, 41, 42))
CD4_T <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(
  1, 4, 5, 13, 15, 28, 31, 36, 39, 40
))

B_cells <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(3, 6, 16, 26, 34))
diff_B_cells <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(9, 22))

mystery_1 <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(30))
mystery_2 <- WhichCells(so, expression = `wsnn_res.0.8` %in% c(32))

```

```{r assign_cells}
so$CellType <- "Not Assigned"
so@meta.data[B_cells, "CellType"] <- "B"
so@meta.data[diff_B_cells, "CellType"] <- "Differentiated B"
so@meta.data[CD8_T, "CellType"] <- "CD8 T"
so@meta.data[CD4_T, "CellType"] <- "CD4 T"
so@meta.data[Mem_eff_T_cells, "CellType"] <- "CD8 Memory Eff T"
so@meta.data[NKT_cells, "CellType"] <- "NKT"
so@meta.data[proliferting_T, "CellType"] <- "Proliferating T"
so@meta.data[GD_T, "CellType"] <- "GD T"
so@meta.data[NK_CD56_bright, "CellType"] <- "NK CD56 Bright"
so@meta.data[NK_CD56_dim, "CellType"] <- "NK CD56 Dim"
so@meta.data[cDCs, "CellType"] <- "cDC"
so@meta.data[pDCs, "CellType"] <- "pDC"
so@meta.data[CD16_monocytes, "CellType"] <- "CD16 Mono"
so@meta.data[CD14_monocytes, "CellType"] <- "CD14 Mono"
so@meta.data[mystery_1, "CellType"] <- "Unknown #1"
so@meta.data[mystery_2, "CellType"] <- "Unknown #2"
```

``` {r save_data}
faster_saveRDS(
  so$CellType,
  paste0(
    figure_path(),
    "cell_labels.rds"
  )
)
```
